### ISSUE TITLE
소셜 로그인 구현하기

### ISSUE THREAD

**Issue by ImIrondroid** [depromeet/sloth-android#4]
- 구글 로그인 개발 (이지훈)
- 카카오 로그인 개발 (최철훈)
- 애플 로그인 개발 (최철훈, 이지훈)

**Comment by Imabubblyiron** [comment]
카카오 로그인을 사용하기 위한 설정을 적용하고 코드를 추가하였습니다.
- https://developers.kakao.com/ 에 프로젝트 등록 후 로그인을 위한 설정 완료
- 안드로이드 소스 코드 내에서 네이티브 앱 키 등록
